# Generated by Django 5.0.1 on 2024-01-15 01:22

import django.db.models.deletion
import e_students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('digitalAddress', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('program_offered', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year_of_admission', models.CharField(max_length=255)),
                ('year_of_completion', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=e_students.models.upload_student_image)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
